-- Generated by scripts/seed-risk-prompts.mjs from data/risk-prompts/watchtower_default_risk_prompt_library_v1_0.csv.
-- Safe to rerun. Removed CSV rows are intentionally not deleted from the database.

begin;

with upsert_library as (
  insert into public.risk_prompt_libraries (
    risk_library_key,
    risk_library_version,
    name,
    description,
    is_default,
    is_active
  )
  values (
    'watchtower-default',
    '1.0',
    'Watchtower Default Risk Prompt Library V1.0',
    'A structured starter library of common project risk areas and prompts for guided Draft risk creation.',
    true,
    true
  )
  on conflict (risk_library_key, risk_library_version) do update
    set name = excluded.name,
        description = excluded.description,
        is_default = excluded.is_default,
        is_active = excluded.is_active,
        updated_at = now()
  returning id
),
area_source (risk_area_key, risk_area_title, risk_area_order, is_active) as (
  values
    ('governance-decision-making', 'Governance and decision-making', 1, true),
    ('scope-requirements', 'Scope and requirements', 2, true),
    ('schedule-milestones', 'Schedule and milestones', 3, true),
    ('financial-commercial', 'Financial and commercial', 4, true),
    ('people-skills-capacity', 'People, skills and capacity', 5, true),
    ('stakeholders-communications', 'Stakeholders and communications', 6, true),
    ('technology-architecture', 'Technology and architecture', 7, true),
    ('data-privacy-security', 'Data, privacy and security', 8, true),
    ('suppliers-dependencies', 'Suppliers and dependencies', 9, true),
    ('quality-testing-acceptance', 'Quality, testing and acceptance', 10, true),
    ('change-adoption', 'Change and adoption', 11, true),
    ('operational-readiness-transition', 'Operational readiness and transition', 12, true)
),
upsert_areas as (
  insert into public.risk_prompt_areas (
    risk_prompt_library_id,
    risk_area_key,
    risk_area_title,
    risk_area_order,
    is_active
  )
  select
    upsert_library.id,
    area_source.risk_area_key,
    area_source.risk_area_title,
    area_source.risk_area_order,
    area_source.is_active
  from upsert_library
  cross join area_source
  on conflict (risk_prompt_library_id, risk_area_key) do update
    set risk_area_title = excluded.risk_area_title,
        risk_area_order = excluded.risk_area_order,
        is_active = excluded.is_active,
        updated_at = now()
  returning id, risk_area_key
)
select count(*) from upsert_areas;

do $$
declare
  target_library_id uuid;
  conflicting_prompt_id text;
begin
  select id into target_library_id
  from public.risk_prompt_libraries
  where risk_library_key = 'watchtower-default'
    and risk_library_version = '1.0';

  select risk_prompt_id into conflicting_prompt_id
  from public.risk_prompts
  where risk_prompt_id in ('WT-RP-001', 'WT-RP-002', 'WT-RP-003', 'WT-RP-004', 'WT-RP-005', 'WT-RP-006', 'WT-RP-007', 'WT-RP-008', 'WT-RP-009', 'WT-RP-010', 'WT-RP-011', 'WT-RP-012', 'WT-RP-013', 'WT-RP-014', 'WT-RP-015', 'WT-RP-016', 'WT-RP-017', 'WT-RP-018', 'WT-RP-019', 'WT-RP-020', 'WT-RP-021', 'WT-RP-022', 'WT-RP-023', 'WT-RP-024', 'WT-RP-025', 'WT-RP-026', 'WT-RP-027', 'WT-RP-028', 'WT-RP-029', 'WT-RP-030', 'WT-RP-031', 'WT-RP-032', 'WT-RP-033', 'WT-RP-034', 'WT-RP-035', 'WT-RP-036', 'WT-RP-037', 'WT-RP-038', 'WT-RP-039', 'WT-RP-040', 'WT-RP-041', 'WT-RP-042', 'WT-RP-043', 'WT-RP-044', 'WT-RP-045', 'WT-RP-046', 'WT-RP-047', 'WT-RP-048', 'WT-RP-049', 'WT-RP-050', 'WT-RP-051', 'WT-RP-052', 'WT-RP-053', 'WT-RP-054', 'WT-RP-055', 'WT-RP-056', 'WT-RP-057', 'WT-RP-058', 'WT-RP-059', 'WT-RP-060', 'WT-RP-061', 'WT-RP-062', 'WT-RP-063', 'WT-RP-064', 'WT-RP-065', 'WT-RP-066', 'WT-RP-067', 'WT-RP-068', 'WT-RP-069', 'WT-RP-070', 'WT-RP-071', 'WT-RP-072', 'WT-RP-073', 'WT-RP-074', 'WT-RP-075', 'WT-RP-076', 'WT-RP-077', 'WT-RP-078', 'WT-RP-079', 'WT-RP-080', 'WT-RP-081', 'WT-RP-082', 'WT-RP-083', 'WT-RP-084', 'WT-RP-085', 'WT-RP-086', 'WT-RP-087', 'WT-RP-088', 'WT-RP-089', 'WT-RP-090', 'WT-RP-091', 'WT-RP-092', 'WT-RP-093', 'WT-RP-094', 'WT-RP-095', 'WT-RP-096')
    and risk_prompt_library_id <> target_library_id
  limit 1;

  if conflicting_prompt_id is not null then
    raise exception 'risk_prompt_id % already belongs to a different library version', conflicting_prompt_id;
  end if;
end $$;

with target_library as (
  select id
  from public.risk_prompt_libraries
  where risk_library_key = 'watchtower-default'
    and risk_library_version = '1.0'
),
prompt_source (
  risk_prompt_id,
  risk_area_key,
  risk_prompt_title,
  risk_prompt_guidance,
  risk_prompt_order,
  risk_prompt_is_active,
  risk_default_status,
  risk_source_reference,
  risk_tags
) as (
  values
    ('WT-RP-001', 'governance-decision-making', 'Decision-making authority is unclear', 'Key decisions may be delayed or challenged because authority, escalation routes or delegated limits are not clearly defined.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'decision-making', 'authority']::text[]),
    ('WT-RP-002', 'governance-decision-making', 'Governance forums are not operating effectively', 'Governance meetings may not have the right attendance, information, cadence or decision focus to support timely project control.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'meetings', 'oversight']::text[]),
    ('WT-RP-003', 'governance-decision-making', 'Critical decisions are overdue', 'Delivery may be affected because important decisions have not been made by the required date.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'decisions', 'delay']::text[]),
    ('WT-RP-004', 'governance-decision-making', 'Escalation routes are unclear or unused', 'Material concerns may remain unresolved because teams do not know when, how or to whom they should escalate.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'escalation', 'accountability']::text[]),
    ('WT-RP-005', 'governance-decision-making', 'Project accountabilities are not clearly assigned', 'Work, decisions or assurance activities may be missed because accountable roles are unclear or overlap.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'roles', 'accountability']::text[]),
    ('WT-RP-006', 'governance-decision-making', 'Governance information is incomplete or unreliable', 'Leaders may make poor decisions because reporting is late, inconsistent, incomplete or based on unverified information.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'reporting', 'data-quality']::text[]),
    ('WT-RP-007', 'governance-decision-making', 'Assurance findings are not being actioned', 'Known weaknesses may persist because assurance recommendations do not have owners, actions or due dates.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'assurance', 'actions']::text[]),
    ('WT-RP-008', 'governance-decision-making', 'Project objectives are not aligned with organisational priorities', 'The project may lose support, funding or relevance if its objectives no longer align with wider organisational priorities.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['governance', 'strategy', 'alignment']::text[]),
    ('WT-RP-009', 'scope-requirements', 'Project scope is unclear', 'Teams and stakeholders may hold different views of what is included, excluded or expected from the project.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['scope', 'clarity', 'alignment']::text[]),
    ('WT-RP-010', 'scope-requirements', 'Requirements are incomplete', 'Delivery may be delayed or reworked because important business, user, technical or operational requirements have not been identified.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['requirements', 'completeness', 'rework']::text[]),
    ('WT-RP-011', 'scope-requirements', 'Requirements are changing without control', 'Uncontrolled changes may increase cost, extend timelines or reduce delivery confidence.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['requirements', 'change-control', 'scope-creep']::text[]),
    ('WT-RP-012', 'scope-requirements', 'Acceptance criteria are unclear', 'Outputs may be disputed or rejected because completion and acceptance conditions are not sufficiently defined.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['requirements', 'acceptance', 'quality']::text[]),
    ('WT-RP-013', 'scope-requirements', 'Dependencies between requirements are not understood', 'Changes to one requirement may create unintended consequences elsewhere in the solution or delivery plan.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['requirements', 'dependencies', 'impact']::text[]),
    ('WT-RP-014', 'scope-requirements', 'Stakeholder needs conflict', 'Different stakeholder groups may expect incompatible outcomes, creating delay, compromise or dissatisfaction.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['requirements', 'stakeholders', 'conflict']::text[]),
    ('WT-RP-015', 'scope-requirements', 'Non-functional requirements are underdefined', 'Security, performance, accessibility, reliability or support needs may be discovered too late.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['requirements', 'non-functional', 'quality']::text[]),
    ('WT-RP-016', 'scope-requirements', 'Scope boundaries do not reflect available time or budget', 'The agreed scope may not be achievable within the approved delivery constraints.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['scope', 'budget', 'schedule', 'feasibility']::text[]),
    ('WT-RP-017', 'schedule-milestones', 'The delivery plan is not credible', 'The schedule may not reflect realistic effort, sequencing, dependencies, capacity or uncertainty.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'planning', 'credibility']::text[]),
    ('WT-RP-018', 'schedule-milestones', 'A critical milestone is at risk', 'A key delivery, governance, contractual or operational milestone may not be achieved on time.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'milestones', 'delay']::text[]),
    ('WT-RP-019', 'schedule-milestones', 'Critical path activities are not understood', 'The project may focus on lower-priority work while activities that directly control the end date are missed.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'critical-path', 'planning']::text[]),
    ('WT-RP-020', 'schedule-milestones', 'Schedule contingency is insufficient', 'The project may have little ability to absorb delay, rework or emerging dependencies.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'contingency', 'resilience']::text[]),
    ('WT-RP-021', 'schedule-milestones', 'Progress reporting does not reflect actual delivery', 'Reported progress may overstate completion or hide blocked, incomplete or unaccepted work.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'reporting', 'progress']::text[]),
    ('WT-RP-022', 'schedule-milestones', 'Key dates depend on unconfirmed assumptions', 'Milestones may move if planning assumptions about approvals, resources, suppliers or environments prove incorrect.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'assumptions', 'dependencies']::text[]),
    ('WT-RP-023', 'schedule-milestones', 'Delivery sequencing is inefficient', 'Work may be started in the wrong order, creating avoidable waiting, hand-offs or rework.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'sequencing', 'flow']::text[]),
    ('WT-RP-024', 'schedule-milestones', 'External deadlines are driving unsafe compression', 'A fixed deadline may lead to reduced quality, skipped assurance or unrealistic delivery commitments.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['schedule', 'deadline', 'quality']::text[]),
    ('WT-RP-025', 'financial-commercial', 'Project costs may exceed the approved budget', 'Current forecasts, commitments or emerging work may cause total costs to exceed available funding.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['finance', 'budget', 'forecast']::text[]),
    ('WT-RP-026', 'financial-commercial', 'Cost estimates are unreliable', 'Budget decisions may be based on incomplete assumptions, poor data or insufficient estimation detail.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['finance', 'estimation', 'uncertainty']::text[]),
    ('WT-RP-027', 'financial-commercial', 'Benefits may not justify the investment', 'Expected benefits may be overstated, delayed, unmeasured or no longer aligned with the business case.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['finance', 'benefits', 'business-case']::text[]),
    ('WT-RP-028', 'financial-commercial', 'Funding is not secured for the full delivery period', 'The project may pause, reduce scope or incur inefficiency if future funding is uncertain.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['finance', 'funding', 'continuity']::text[]),
    ('WT-RP-029', 'financial-commercial', 'Commercial terms do not protect the project', 'Contracts may not provide adequate clarity, incentives, remedies, responsibilities or change control.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['commercial', 'contracts', 'risk']::text[]),
    ('WT-RP-030', 'financial-commercial', 'Supplier costs are increasing', 'Price changes, currency movements, indexation or additional supplier effort may increase total project cost.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['commercial', 'supplier', 'cost']::text[]),
    ('WT-RP-031', 'financial-commercial', 'Financial reporting is delayed or incomplete', 'Leaders may not identify overspend, commitments or forecast variance early enough to intervene.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['finance', 'reporting', 'controls']::text[]),
    ('WT-RP-032', 'financial-commercial', 'Procurement lead times threaten delivery', 'Required goods or services may not be contracted or available in time to support the plan.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['commercial', 'procurement', 'schedule']::text[]),
    ('WT-RP-033', 'people-skills-capacity', 'Critical skills are unavailable', 'The project may be unable to complete specialist work because required capability is missing or constrained.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'skills', 'capability']::text[]),
    ('WT-RP-034', 'people-skills-capacity', 'The team does not have enough capacity', 'Committed work may exceed the available time and capacity of the delivery team.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'capacity', 'planning']::text[]),
    ('WT-RP-035', 'people-skills-capacity', 'Key-person dependency is too high', 'Loss or unavailability of a small number of individuals could materially disrupt delivery.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'key-person', 'resilience']::text[]),
    ('WT-RP-036', 'people-skills-capacity', 'Roles and responsibilities are unclear', 'Work may be duplicated, delayed or missed because responsibilities and decision rights are not understood.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'roles', 'accountability']::text[]),
    ('WT-RP-037', 'people-skills-capacity', 'Team turnover is affecting continuity', 'Knowledge loss and onboarding demand may reduce productivity, quality or delivery confidence.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'turnover', 'continuity']::text[]),
    ('WT-RP-038', 'people-skills-capacity', 'The team is experiencing sustained overload', 'Excessive workload may lead to burnout, absence, reduced quality or further attrition.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'wellbeing', 'capacity']::text[]),
    ('WT-RP-039', 'people-skills-capacity', 'Required training has not been completed', 'Users or delivery teams may be unable to operate, support or govern the new capability effectively.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'training', 'readiness']::text[]),
    ('WT-RP-040', 'people-skills-capacity', 'The delivery model relies on unavailable stakeholders', 'Progress may depend on business, technical or governance contributors who cannot provide timely input.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['people', 'stakeholders', 'availability']::text[]),
    ('WT-RP-041', 'stakeholders-communications', 'Key stakeholders are not sufficiently engaged', 'Decisions, approvals, adoption or support may be delayed because influential stakeholders are not involved.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['stakeholders', 'engagement', 'governance']::text[]),
    ('WT-RP-042', 'stakeholders-communications', 'Stakeholder expectations are not aligned', 'Different groups may hold conflicting views about outcomes, timing, quality or responsibilities.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['stakeholders', 'expectations', 'alignment']::text[]),
    ('WT-RP-043', 'stakeholders-communications', 'Project communications are ineffective', 'Important information may not reach the right people in a timely, clear or usable form.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['communications', 'stakeholders', 'clarity']::text[]),
    ('WT-RP-044', 'stakeholders-communications', 'A key stakeholder opposes the proposed change', 'Active resistance may delay approval, reduce adoption or undermine delivery outcomes.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['stakeholders', 'resistance', 'change']::text[]),
    ('WT-RP-045', 'stakeholders-communications', 'Decision-makers do not have enough information', 'Approvals may be delayed or made on weak evidence because decision packs are incomplete or unclear.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['stakeholders', 'decisions', 'information']::text[]),
    ('WT-RP-046', 'stakeholders-communications', 'Stakeholder feedback is not being incorporated', 'The delivered outcome may fail to meet real needs if feedback is collected but not evaluated or acted upon.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['stakeholders', 'feedback', 'requirements']::text[]),
    ('WT-RP-047', 'stakeholders-communications', 'There is no shared understanding of project status', 'Teams and leaders may make inconsistent decisions because status, risks and priorities are communicated differently.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['communications', 'status', 'alignment']::text[]),
    ('WT-RP-048', 'stakeholders-communications', 'Sensitive messages may be communicated poorly', 'Trust or reputation may be damaged if difficult decisions, delays or impacts are not handled carefully.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['communications', 'reputation', 'trust']::text[]),
    ('WT-RP-049', 'technology-architecture', 'The proposed solution architecture is not proven', 'Key design assumptions may fail under real operational, security, integration or scale conditions.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'architecture', 'assumptions']::text[]),
    ('WT-RP-050', 'technology-architecture', 'Legacy technology constrains the solution', 'Older platforms, unsupported components or technical debt may limit delivery options or increase effort.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'legacy', 'technical-debt']::text[]),
    ('WT-RP-051', 'technology-architecture', 'Integration complexity is underestimated', 'Interfaces, data contracts, sequencing or ownership may require more effort than planned.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'integration', 'complexity']::text[]),
    ('WT-RP-052', 'technology-architecture', 'The solution may not scale as required', 'Performance or capacity may degrade as users, data volumes or transaction demand increase.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'scalability', 'performance']::text[]),
    ('WT-RP-053', 'technology-architecture', 'Technical environments are not available when needed', 'Development, test, staging or production work may be blocked by delayed or unstable environments.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'environments', 'schedule']::text[]),
    ('WT-RP-054', 'technology-architecture', 'Critical technical decisions are unresolved', 'Delivery may continue on unstable assumptions while key architecture or platform choices remain open.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'decisions', 'architecture']::text[]),
    ('WT-RP-055', 'technology-architecture', 'Third-party technology may become unsupported', 'A vendor, library, platform or component may reach end of life or lose required support.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'vendor', 'obsolescence']::text[]),
    ('WT-RP-056', 'technology-architecture', 'Technical debt is being accepted without a recovery plan', 'Short-term delivery choices may create material future cost, fragility or operational risk.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['technology', 'technical-debt', 'maintainability']::text[]),
    ('WT-RP-057', 'data-privacy-security', 'Sensitive data may be accessed without authorisation', 'Access controls, permissions or segregation may not adequately protect confidential or personal information.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['data', 'security', 'access-control']::text[]),
    ('WT-RP-058', 'data-privacy-security', 'Personal data processing may not meet legal requirements', 'The project may not adequately address lawful basis, transparency, minimisation, retention or data-subject rights.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['data', 'privacy', 'gdpr']::text[]),
    ('WT-RP-059', 'data-privacy-security', 'Data quality is insufficient for the intended use', 'Inaccurate, incomplete, duplicated or stale data may undermine decisions, automation or user trust.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['data', 'data-quality', 'operations']::text[]),
    ('WT-RP-060', 'data-privacy-security', 'Security requirements are incomplete', 'Threats and required controls may be discovered late because security needs have not been fully defined.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['security', 'requirements', 'assurance']::text[]),
    ('WT-RP-061', 'data-privacy-security', 'A cyber incident could materially disrupt delivery', 'The project may be exposed to malware, credential compromise, denial of service or other cyber threats.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['security', 'cyber', 'resilience']::text[]),
    ('WT-RP-062', 'data-privacy-security', 'Data migration may fail or lose information', 'Data may be corrupted, omitted, duplicated or incorrectly transformed during migration.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['data', 'migration', 'quality']::text[]),
    ('WT-RP-063', 'data-privacy-security', 'Retention and deletion rules are unclear', 'Information may be kept too long, deleted too early or handled inconsistently.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['data', 'retention', 'privacy']::text[]),
    ('WT-RP-064', 'data-privacy-security', 'Third parties may not protect data adequately', 'Suppliers or processors may introduce privacy, security, sovereignty or contractual exposure.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['data', 'third-party', 'security']::text[]),
    ('WT-RP-065', 'suppliers-dependencies', 'A critical supplier may not deliver on time', 'The project may be delayed because a supplier cannot meet agreed dates, quality or capacity.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['supplier', 'schedule', 'dependency']::text[]),
    ('WT-RP-066', 'suppliers-dependencies', 'Supplier performance is below expectation', 'Repeated defects, missed commitments or slow response may undermine delivery confidence.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['supplier', 'performance', 'quality']::text[]),
    ('WT-RP-067', 'suppliers-dependencies', 'A critical external dependency is not controlled', 'The project relies on work, approval, data or capability outside its direct authority.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['dependency', 'external', 'control']::text[]),
    ('WT-RP-068', 'suppliers-dependencies', 'Dependency owners are unclear', 'Required actions may not be completed because accountability for the dependency is not agreed.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['dependency', 'ownership', 'accountability']::text[]),
    ('WT-RP-069', 'suppliers-dependencies', 'Supplier exit or failure would disrupt delivery', 'The project may not have viable alternatives, transition plans or access to required assets and knowledge.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['supplier', 'resilience', 'continuity']::text[]),
    ('WT-RP-070', 'suppliers-dependencies', 'Contract changes are delaying progress', 'Commercial negotiation or formal variation may prevent work from starting or continuing.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['supplier', 'contract', 'delay']::text[]),
    ('WT-RP-071', 'suppliers-dependencies', 'Third-party lead times are longer than planned', 'Hardware, licences, services, approvals or specialist resources may not arrive when required.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['supplier', 'lead-time', 'schedule']::text[]),
    ('WT-RP-072', 'suppliers-dependencies', 'Multiple suppliers are not coordinating effectively', 'Gaps, overlaps or disputes between suppliers may cause integration failure or unclear accountability.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['supplier', 'coordination', 'integration']::text[]),
    ('WT-RP-073', 'quality-testing-acceptance', 'Testing scope is insufficient', 'Important functional, non-functional, security, accessibility or operational scenarios may not be tested.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'testing', 'coverage']::text[]),
    ('WT-RP-074', 'quality-testing-acceptance', 'Defect levels are higher than expected', 'The volume or severity of defects may threaten milestones, acceptance or operational stability.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'defects', 'delivery']::text[]),
    ('WT-RP-075', 'quality-testing-acceptance', 'Test environments or data are not fit for purpose', 'Testing may produce unreliable results because environments, integrations or datasets do not reflect required conditions.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'testing', 'environments']::text[]),
    ('WT-RP-076', 'quality-testing-acceptance', 'Acceptance responsibility is unclear', 'Outputs may remain unapproved because the correct approver, evidence or acceptance process is not defined.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'acceptance', 'governance']::text[]),
    ('WT-RP-077', 'quality-testing-acceptance', 'Quality controls are being reduced to meet dates', 'Schedule pressure may lead to skipped reviews, incomplete testing or acceptance of avoidable defects.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'schedule', 'assurance']::text[]),
    ('WT-RP-078', 'quality-testing-acceptance', 'Non-functional performance is not validated', 'The solution may fail under expected load, resilience, usability or recovery conditions.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'performance', 'non-functional']::text[]),
    ('WT-RP-079', 'quality-testing-acceptance', 'Known defects do not have an agreed treatment', 'Unresolved defects may enter production without clear acceptance, mitigation or ownership.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'defects', 'risk-acceptance']::text[]),
    ('WT-RP-080', 'quality-testing-acceptance', 'User acceptance testing is not representative', 'Testing may not reflect real user roles, workflows, data or operating conditions.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['quality', 'uat', 'users']::text[]),
    ('WT-RP-081', 'change-adoption', 'Users may not adopt the new capability', 'Expected benefits may not be realised if users continue with existing tools, workarounds or behaviours.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'adoption', 'benefits']::text[]),
    ('WT-RP-082', 'change-adoption', 'The change impact is not understood', 'Teams may be unprepared for changes to roles, processes, controls, skills or workload.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'impact', 'readiness']::text[]),
    ('WT-RP-083', 'change-adoption', 'Change communications are starting too late', 'Users may not understand why the change is happening, what it means or what action they need to take.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'communications', 'engagement']::text[]),
    ('WT-RP-084', 'change-adoption', 'Training is insufficient for affected users', 'Users may make errors, avoid the capability or require excessive support after launch.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'training', 'readiness']::text[]),
    ('WT-RP-085', 'change-adoption', 'Business readiness is not being measured', 'The project may go live without evidence that people, process, support and governance are prepared.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'business-readiness', 'assurance']::text[]),
    ('WT-RP-086', 'change-adoption', 'Local teams are creating inconsistent workarounds', 'Different adoption approaches may undermine standardisation, data quality or control.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'workarounds', 'consistency']::text[]),
    ('WT-RP-087', 'change-adoption', 'Benefits ownership is unclear', 'Expected outcomes may not be tracked or sustained because no one is accountable for realisation.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'benefits', 'ownership']::text[]),
    ('WT-RP-088', 'change-adoption', 'Leadership sponsorship is weakening', 'Loss of visible support may reduce urgency, participation, funding or confidence in the change.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['change', 'sponsorship', 'leadership']::text[]),
    ('WT-RP-089', 'operational-readiness-transition', 'Operational ownership is not confirmed', 'The delivered capability may not have a clearly accountable team to operate, support or improve it.', 1, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'ownership', 'transition']::text[]),
    ('WT-RP-090', 'operational-readiness-transition', 'Support arrangements are incomplete', 'Users may not receive timely help because support routes, service levels, tools or responsibilities are unclear.', 2, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'support', 'readiness']::text[]),
    ('WT-RP-091', 'operational-readiness-transition', 'Cutover planning is incomplete', 'Go-live may fail or cause disruption because tasks, sequencing, decisions and rollback arrangements are not fully defined.', 3, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'cutover', 'go-live']::text[]),
    ('WT-RP-092', 'operational-readiness-transition', 'Business continuity arrangements are inadequate', 'The organisation may be unable to maintain critical services if the new capability fails.', 4, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'continuity', 'resilience']::text[]),
    ('WT-RP-093', 'operational-readiness-transition', 'Operational procedures are not documented', 'Teams may operate inconsistently or rely on individual knowledge after transition.', 5, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'procedures', 'knowledge']::text[]),
    ('WT-RP-094', 'operational-readiness-transition', 'Monitoring and alerting are insufficient', 'Operational problems may not be detected or acted upon quickly after deployment.', 6, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'monitoring', 'support']::text[]),
    ('WT-RP-095', 'operational-readiness-transition', 'A rollback or recovery approach is not viable', 'The project may be unable to restore service safely if implementation fails.', 7, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'rollback', 'recovery']::text[]),
    ('WT-RP-096', 'operational-readiness-transition', 'Post-implementation review and improvement are not planned', 'Lessons, defects and benefit gaps may remain unresolved after launch.', 8, true, 'draft', 'Watchtower Default Risk Prompt Library V1.0', array['operations', 'review', 'continuous-improvement']::text[])
)
insert into public.risk_prompts (
  risk_prompt_library_id,
  risk_prompt_area_id,
  risk_prompt_id,
  risk_prompt_title,
  risk_prompt_guidance,
  risk_prompt_order,
  risk_prompt_is_active,
  risk_default_status,
  risk_source_reference,
  risk_tags
)
select
  target_library.id,
  risk_prompt_areas.id,
  prompt_source.risk_prompt_id,
  prompt_source.risk_prompt_title,
  prompt_source.risk_prompt_guidance,
  prompt_source.risk_prompt_order,
  prompt_source.risk_prompt_is_active,
  prompt_source.risk_default_status,
  prompt_source.risk_source_reference,
  prompt_source.risk_tags
from target_library
join prompt_source on true
join public.risk_prompt_areas
  on risk_prompt_areas.risk_prompt_library_id = target_library.id
 and risk_prompt_areas.risk_area_key = prompt_source.risk_area_key
on conflict (risk_prompt_id) do update
  set risk_prompt_title = excluded.risk_prompt_title,
      risk_prompt_guidance = excluded.risk_prompt_guidance,
      risk_prompt_order = excluded.risk_prompt_order,
      risk_prompt_is_active = excluded.risk_prompt_is_active,
      risk_default_status = excluded.risk_default_status,
      risk_source_reference = excluded.risk_source_reference,
      risk_tags = excluded.risk_tags,
      risk_prompt_area_id = excluded.risk_prompt_area_id,
      updated_at = now();

commit;
