import type { TimelineAdapterContext, TimelineSourceAdapter } from './timelineAdapter.ts';
import type { TimelineEvent } from './timelineTypes.ts';

const FIXTURE_SOURCE = 'timeline-foundation-003-fixture';

type FixtureEventSeed = Omit<TimelineEvent, 'workspaceId' | 'projectId' | 'canView' | 'canEdit' | 'canMove' | 'allDay'>;
export type TimelineFixtureOptions = {
	includeProjectDelivery?: boolean;
	includeRaid?: boolean;
};

const TIMELINE_FIXTURE_EVENT_SEEDS: FixtureEventSeed[] = [
	{
		id: 'fixture-planned-uat',
		sourceType: 'project-date',
		sourceId: 'fixture-planned-uat',
		sourceReference: 'UAT',
		title: 'Planned UAT',
		summary: 'Business users validate the core delivery flow before release readiness.',
		category: 'UAT',
		startDate: '2026-07-13',
		endDate: '2026-07-17',
		presentationType: 'range',
		status: 'On track',
		attentionTone: 'green',
		layer: 'project-delivery',
		iconKey: 'uat',
	},
	{
		id: 'fixture-integration-window',
		sourceType: 'project-date',
		sourceId: 'fixture-integration-window',
		sourceReference: 'INT',
		title: 'Integration window',
		summary: 'Integration services are reserved with supplier support still being confirmed.',
		category: 'Integration',
		startDate: '2026-07-14',
		endDate: '2026-07-16',
		presentationType: 'range',
		status: 'Amber',
		attentionTone: 'amber',
		layer: 'project-delivery',
		iconKey: 'integration',
	},
	{
		id: 'fixture-cutover-rehearsal',
		sourceType: 'project-date',
		sourceId: 'fixture-cutover-rehearsal',
		sourceReference: 'CUT',
		title: 'Cutover rehearsal',
		summary: 'Runbook rehearsal overlaps testing so capacity needs careful monitoring.',
		category: 'Cutover',
		startDate: '2026-07-15',
		endDate: '2026-07-18',
		presentationType: 'range',
		status: 'Watch',
		attentionTone: 'amber',
		layer: 'project-delivery',
		iconKey: 'cutover',
	},
	{
		id: 'fixture-training-prep',
		sourceType: 'project-date',
		sourceId: 'fixture-training-prep',
		sourceReference: 'TRN',
		title: 'Training preparation',
		summary: 'Training material is being completed while UAT evidence is gathered.',
		category: 'Training',
		startDate: '2026-07-16',
		endDate: '2026-07-19',
		presentationType: 'range',
		status: 'Upcoming',
		attentionTone: 'neutral',
		layer: 'project-delivery',
		iconKey: 'training',
	},
	{
		id: 'fixture-hypercare-briefing',
		sourceType: 'project-date',
		sourceId: 'fixture-hypercare-briefing',
		sourceReference: 'HYP',
		title: 'Hypercare briefing',
		summary: 'Support model briefing proves range overflow without becoming live data.',
		category: 'Hypercare',
		startDate: '2026-07-16',
		endDate: '2026-07-20',
		presentationType: 'range',
		status: 'Upcoming',
		attentionTone: 'green',
		layer: 'project-delivery',
		iconKey: 'hypercare',
	},
	{
		id: 'fixture-june-checkpoint',
		sourceType: 'project-date',
		sourceId: 'fixture-june-checkpoint',
		sourceReference: 'CHK',
		title: 'June readiness checkpoint',
		summary: 'Adjacent-month checkpoint visible in the July grid.',
		category: 'Review',
		startDate: '2026-06-30',
		presentationType: 'point',
		status: 'Completed',
		attentionTone: 'neutral',
		layer: 'project-delivery',
		iconKey: 'review',
	},
	{
		id: 'fixture-prototype-sign-off',
		sourceType: 'project-date',
		sourceId: 'fixture-prototype-sign-off',
		sourceReference: 'MS-020',
		title: 'Prototype sign-off',
		summary: 'Milestone for confirming the prototype remains ready for stakeholder review.',
		category: 'Milestone',
		startDate: '2026-07-20',
		presentationType: 'point',
		status: 'Upcoming',
		attentionTone: 'green',
		layer: 'project-delivery',
		iconKey: 'milestone',
	},
	{
		id: 'fixture-weekend-release-rehearsal',
		sourceType: 'project-date',
		sourceId: 'fixture-weekend-release-rehearsal',
		sourceReference: 'REL',
		title: 'Weekend release rehearsal',
		summary: 'Weekend fixture proves that bars and selected states remain readable.',
		category: 'Deployment',
		startDate: '2026-08-01',
		endDate: '2026-08-02',
		presentationType: 'range',
		status: 'Planned',
		attentionTone: 'neutral',
		layer: 'project-delivery',
		iconKey: 'deployment',
	},
	{
		id: 'fixture-risk-review',
		sourceType: 'risk',
		sourceId: 'fixture-risk-review',
		sourceReference: 'RISK-WAT-010',
		title: 'Risk review',
		summary: 'Review open delivery risks before the UAT exit decision.',
		startDate: '2026-07-16',
		presentationType: 'point',
		status: 'Scheduled',
		attentionTone: 'neutral',
		layer: 'risks',
		iconKey: 'risk',
	},
	{
		id: 'fixture-risk-supplier-environment',
		sourceType: 'risk',
		sourceId: 'fixture-risk-supplier-environment',
		sourceReference: 'RISK-WAT-012',
		title: 'Supplier environment may not be ready',
		summary: 'Supplier test environment readiness is still unresolved.',
		startDate: '2026-07-16',
		presentationType: 'point',
		status: 'Red',
		attentionTone: 'red',
		layer: 'risks',
		iconKey: 'risk',
	},
	{
		id: 'fixture-risk-resource',
		sourceType: 'risk',
		sourceId: 'fixture-risk-resource',
		sourceReference: 'RISK-WAT-018',
		title: 'Key resource availability uncertain',
		summary: 'A named SME may be unavailable during the integrated test window.',
		startDate: '2026-07-16',
		presentationType: 'point',
		status: 'Amber',
		attentionTone: 'amber',
		layer: 'risks',
		iconKey: 'risk',
	},
	{
		id: 'fixture-issue-environment',
		sourceType: 'issue',
		sourceId: 'fixture-issue-environment',
		sourceReference: 'ISSUE-WAT-006',
		title: 'Test environment unstable',
		summary: 'Intermittent failures are slowing test execution and need triage.',
		startDate: '2026-07-15',
		presentationType: 'point',
		status: 'Red',
		attentionTone: 'red',
		layer: 'issues',
		iconKey: 'issue',
	},
	{
		id: 'fixture-issue-defect-triage',
		sourceType: 'issue',
		sourceId: 'fixture-issue-defect-triage',
		sourceReference: 'ISSUE-WAT-009',
		title: 'Defect triage checkpoint',
		summary: 'Extra same-day issue fixture proves point overflow handling.',
		startDate: '2026-07-16',
		presentationType: 'point',
		status: 'Open',
		attentionTone: 'amber',
		layer: 'issues',
		iconKey: 'issue',
	},
	{
		id: 'fixture-dependency-api',
		sourceType: 'dependency',
		sourceId: 'fixture-dependency-api',
		sourceReference: 'DEP-WAT-007',
		title: 'Third-party API handover',
		summary: 'API handover is due before integration test evidence can be closed.',
		startDate: '2026-07-16',
		presentationType: 'point',
		status: 'Amber',
		attentionTone: 'amber',
		layer: 'dependencies',
		iconKey: 'dependency',
	},
	{
		id: 'fixture-decision-staging',
		sourceType: 'decision',
		sourceId: 'fixture-decision-staging',
		sourceReference: 'DEC-WAT-009',
		title: 'Approve staging environment build',
		summary: 'Decision required to proceed with the staging build plan.',
		startDate: '2026-07-17',
		presentationType: 'point',
		status: 'Pending',
		attentionTone: 'amber',
		layer: 'decisions',
		iconKey: 'decision',
	},
	{
		id: 'fixture-action-hidden',
		sourceType: 'action',
		sourceId: 'fixture-action-hidden',
		sourceReference: 'ACT-WAT-004',
		title: 'Confirm support rota',
		summary: 'Action fixture remains hidden by default to prove layer defaults.',
		startDate: '2026-07-16',
		presentationType: 'point',
		status: 'Open',
		attentionTone: 'amber',
		layer: 'actions',
		iconKey: 'action',
	},
];

export function createTimelineFixtureEvents(
	context: Pick<TimelineAdapterContext, 'workspaceId' | 'projectId'>,
	options: TimelineFixtureOptions = {},
): TimelineEvent[] {
	const includeProjectDelivery = options.includeProjectDelivery ?? false;
	const includeRaid = options.includeRaid ?? true;
	return TIMELINE_FIXTURE_EVENT_SEEDS.filter((event) => (
		(event.sourceType === 'project-date' && includeProjectDelivery)
		|| (event.sourceType !== 'project-date' && includeRaid)
	)).map((event) => ({
		...event,
		id: `${FIXTURE_SOURCE}:${event.id}`,
		sourceId: `${FIXTURE_SOURCE}:${event.sourceId}`,
		workspaceId: context.workspaceId,
		projectId: context.projectId,
		allDay: true,
		canView: true,
		canEdit: false,
		canMove: false,
		lockedReason: 'Fixture event only. Source editing is outside WT-TIMELINE-FOUNDATION-003.',
	}));
}

export function createTimelineFixtureAdapter(options: TimelineFixtureOptions = {}): TimelineSourceAdapter {
	return {
		sourceType: 'project-date',
		getEvents: async (context) => createTimelineFixtureEvents(context, options),
	};
}
